
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "asrNuanceWs",
  config: [
    /** OPTIONAL a persistent user pseudonym (should not be traceable/enable reverse-lookup of user); must be URI-encoded/conformant (e.g. user encodeURIComponent()) */
    "userId",
    /** credentials application key (MUST be set via configuration or options) */
    "appKey",
    /** credentials application ID (MUST be set via configuration or options) */
    "appId",
    /** OPTIONAL
     * @default "speex" (see mmir-plugin-encoder-core) */
    "encoder"
  ],
  remoteUrls: {
    baseUrl: "wss://httpapi.labs.nuance.com/v1"
  }
};
