
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *        Do not modify: ANY CHANGES WILL GET DISCARDED              *
 *********************************************************************/

module.exports = {
  pluginName: "asrNuanceWs",
  config: [
    /** OPTIONAL a persistent user pseudonym (should not be traceable/enable reverse-lookup of user); must be URI-encoded/conformant (e.g. user encodeURIComponent()) */
    "userId",
    /** credentials application key (MUST be set via configuration or options) */
    "appKey",
    /** credentials application ID (MUST be set via configuration or options) */
    "appId",
    /** OPTIONAL (see mmir-plugin-encoder-core)
     * @default "speex" */
    "encoder",
    /**
     * the plugin type
     * @default "asr"
     */
    "type",
    /** the plugin/module which which will load/use this specific ASR implementation
     * @default mmir-plugin-encoder-core.js
     */
    "mod"
  ],
  defaultValues: {
    userId: null,
    appKey: null,
    appId: null,
    encoder: "speex",
    type: "asr",
    mod: "mmir-plugin-encoder-core.js"
  },
  remoteUrls: {
    baseUrl: "wss://httpapi.labs.nuance.com/v1"
  }
};
